[package]
name = "leafrs"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.3"
numpy = "0.15"
ordered-float = "2.10.0"

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]
