name: Auto assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  auto-assign-issue:
    runs-on: ubuntu-latest
    steps:
    - name: 'Auto assign issue'
      uses: pozil/auto-assign-issue@v1
      with:
        assignees: willeagren
        numOfAssigne: 1
        allowSelfAssign: true
  
  auto-assign-PR:
    runs-on: ubuntu-latest
    steps:
    - name: 'Auto assign PR'
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.MY_PERSONAL_TOKEN }}
        assignees: willeagren
        numOfAssigne: 1
        allowSelfAssign: true
    