name: Auto assign PR

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: 'Auto assign PR'
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.MY_PERSONAL_TOKEN }}
        assignees: willeagren
        numOfAssignee: 1
        allowSelfAssign: true
