name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout/@v2
    - name: Set up Python3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build
      run: |
        python3 -m pip install --upgrade pip
        make

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout/@v2
    - name: Build
      run: make

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout/@v2
    - name: Build
      run: make

