name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  testsCPU:
    name: CPU Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update packages
      run: sudo apt-get update

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Dependencies, build and test
      run: |
        python3 -m pip install --upgrade pip
        python3 -m venv venv
        source venv/bin/activate
        make
        python3 -m unittest
